djangoProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
    path('', include('likes.urls')),
    path('', include('user.urls')),
    path('__debug__/', include(debug_toolbar.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likes/urls.py
from django.urls import path, include
from likes.views import AddLikeView, RemoveLike

app_name = 'likes'


urlpatterns = [
    path('likes/', include([
        path('add/', AddLikeView.as_view(), name='add'),
        path('remove/', RemoveLike.as_view(), name='remove'),

    ])),
]

user/urls.py
from django.urls import path, include
from user.views import *

urlpatterns = [
    path('user/', include([
        path('user_profile/', get_user_profile, name='user_profile'),
        path('user_profile/<int:pk>/delete', delete_user_account, name='delete_user'),
        path('register/', register, name='register'),
        path('login/', user_login, name='login'),
        path('logout/', user_logout, name='logout'),
    ])),
]

likes/models.py
from django.db import models
from forum.models import Posts
from user.models import User


class PostsLikes(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE, verbose_name='Post in the blog')
    liked_by = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Liked by')
    like = models.BooleanField(default=False, verbose_name='Like')

likes/views.py
from django.shortcuts import redirect
from django.views.generic import View
from forum.models import Posts, User
from likes.models import PostsLikes


class AddLikeView(View):
    def post(self, request, *args, **kwargs):
        post_id = int(request.POST.get('post_id'))
        user_id = int(request.POST.get('user_id'))
        url_from = request.POST.get('url_from')

        current_user = User.objects.get(id=user_id)
        current_post = Posts.objects.get(id=post_id)

        try:
            post_like_inst = PostsLikes.objects.get(post=current_post, liked_by=current_user)
        except Exception as e:
            post_like = PostsLikes(post=current_post, liked_by=current_user, like=True)

            post_like.save()
        return redirect(url_from)


class RemoveLike(View):
    def post(self, request, *args, **kwargs):
        post_likes_id = int(request.POST.get('post_id'))
        url_from = request.POST.get('url_from')

        post_like = PostsLikes.objects.get(id=post_likes_id)
        post_like.delete()

        return redirect(url_from)

templates/inc/_likes.html
{% load likes_post %}

{% is_liked post_id as is_liked_bool %}
{% count_likes post_id as likes_counter %}


{% if is_liked_bool %}
    {% post_likes_id post_id as post_likes_id %}
{% endif %}

<form action="{% if not is_liked_bool %}{% url 'likes:add' %}{% else %}{% url 'likes:remove' %}{% endif %}"
      method="post">
    {% csrf_token %}
    <input type="hidden" name="post_id" value="{{ post_id }}">
    <input type="hidden" name="user_id"
           value="{% if user.is_authenticated %}{{ request.user.id }}{% else %}None{% endif %}">
    <input type="hidden" name="url_from" value="{{ request.path }}">
    {% if is_liked_bool %}
        <input type="hidden" name="post_id" value="{{ post_likes_id }}">
    {% endif %}
    <button type="submit" class="btn btn-danger">

        {% if not is_liked_bool %}
            <i class="bi bi-suit-heart"></i>
        {% else %}
            <i class="bi bi-suit-heart-fill"></i>
        {% endif %}
        <span class="likes-qty">{{ likes_counter }}</span>
    </button>
</form>

templates/inc/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'home' %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'create' %}">Create</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <span class="navbar-text">
                            {% if request.user.is_authenticated %}
                                Hello, <a href="{% url 'user_profile' %}">{{ user.username }}</a> |
                                <a href="{% url 'logout' %}">LOGOUT</a>
                            {% else %}


                                <a href="{% url 'register' %}">register</a> | <a href="{% url 'login' %}"> Login</a>
                            {% endif %}
        </span>
    </div>
</nav>

templates/inc/_sidebar.html
{% load posts_tags %}
{#<div class="list-group">#}
{#    {% get_categories as categories %}#}
{#    {% for item in categories %}#}
{#        <a href="{% url 'category' item.pk %}" class="list-group-item list-group-item-actiom">#}
{#            {{ item.title }}#}
{#        </a>#}
{##}
{#    {% endfor %}#}
{#</div>#}
{##}
{#<br>#}
{% show_categories %}